# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0838babc207a6a00b562b96340794268f3bfdb554925a3127529812183196db25ce6ae6a4fecea7ef0284929dbcc013b0a480044a3921e05faf9022d88862a5b

test:
  secret_key_base: b340e8355d07b481ac3624fc8a504cce6bc054206f54ef06a78ab4b8640c7f44030d0f22f60477719fffb798896e39980e6dd1cdfa3cb2cbce1257d7c1137cad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
